tools = [
    {
        "id": "tool01",
        "name": "Tractor",
        "category": "Heavy Machinery",
        "description": "A large, powerful vehicle used for hauling farm equipment and various tasks like plowing and tilling.",
        "daily_rental_price": 5000,
        "availability": True,
        "condition_rating": 4.5,
    },
    {
        "id": "tool02",
        "name": "Plow",
        "category": "Tillage Implement",
        "description": "An implement used to turn and loosen soil before sowing seeds or planting.",
        "daily_rental_price": 800,
        "availability": True,
         "condition_rating": 4,
    },
    {
        "id": "tool03",
        "name": "Cultivator",
        "category": "Tillage Implement",
        "description": "Used to remove weeds and prepare the soil by breaking up the earth, allowing for better aeration.",
        "daily_rental_price": 750,
        "availability": False,
         "condition_rating": 4.5,
    },
    {
        "id": "tool04",
        "name": "Combine Harvester",
        "category": "Harvesting Machinery",
        "description": "A machine that efficiently harvests crops by reaping, threshing, and winnowing in a single operation.",
        "daily_rental_price": 10000,
        "availability": True,
         "condition_rating": 3.5,
    },
    {
        "id": "tool05",
        "name": "Sprayer Pump",
        "category": "Chemical Application",
        "description": "Used to apply fertilizers, pesticides, and other chemicals to crops, available in various sizes.",
        "daily_rental_price": 500,
        "availability": True,
    },
    {
        "id": "tool06",
        "name": "Rotary Tiller",
        "category": "Tillage Implement",
        "description": "A machine with rotating blades used for tilling and mixing soil to create a smooth seedbed.",
        "daily_rental_price": 1200,
        "availability": True,
    },
    {
        "id": "tool07",
        "name": "Seed Drill",
        "category": "Planting Equipment",
        "description": "A specialized device for sowing seeds precisely into the soil at a controlled depth and rate.",
        "daily_rental_price": 900,
        "availability": False,
    },
    {
        "id": "tool08",
        "name": "Harrow",
        "category": "Tillage Implement",
        "description": "Used after plowing to smooth out the soil surface and create a fine seedbed.",
        "daily_rental_price": 650,
        "availability": True,
    },
    {
        "id": "tool09",
        "name": "Wheelbarrow",
        "category": "Transport",
        "description": "A hand-operated cart with one wheel for transporting heavy or bulky loads around the farm.",
        "daily_rental_price": 100,
        "availability": True,
    },
    {
        "id": "tool10",
        "name": "Sickle",
        "category": "Hand Tool",
        "description": "A small hand tool with a curved blade and a handle, primarily used for harvesting grain.",
        "daily_rental_price": 50,
        "availability": True,
    },
    {
        "id": "tool11",
        "name": "Shovel",
        "category": "Hand Tool",
        "description": "A multi-purpose tool for digging, lifting, and moving materials like soil, sand, and gravel.",
        "daily_rental_price": 40,
        "availability": True,
    },
    {
        "id": "tool12",
        "name": "Hand Fork",
        "category": "Hand Tool",
        "description": "Used for loosening soil around plants and mixing in manure or fertilizer.",
        "daily_rental_price": 30,
        "availability": True,
    },
    {
        "id": "tool13",
        "name": "Earth Auger",
        "category": "Hand Tool",
        "description": "A tool used for digging uniform holes in the ground for tasks like planting or installing fences.",
        "daily_rental_price": 150,
        "availability": True,
    },
    {
        "id": "tool14",
        "name": "Machete",
        "category": "Hand Tool",
        "description": "A versatile tool with a long, heavy blade used for clearing bushes, cutting branches, and harvesting crops.",
        "daily_rental_price": 60,
        "availability": True,
    },
    {
        "id": "tool15",
        "name": "Brush Cutter",
        "category": "Heavy Machinery",
        "description": "A machine used for clearing weeds, overgrown grass, and dense vegetation from a field.",
        "daily_rental_price": 850,
        "availability": False,
    },
]
