# Generated by Django 5.2.7 on 2025-10-17 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="equipment",
        ),
        migrations.AddField(
            model_name="booking",
            name="tool",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="base.tool"
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Equipment",
        ),
    ]
