# Generated by Django 5.2.12 on 2026-03-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
