# Generated by Django 5.2.12 on 2026-03-31 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_userprofile_location"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={"ordering": ["-createdAt"], "verbose_name_plural": "Reviews"},
        ),
        migrations.RemoveField(
            model_name="review",
            name="name",
        ),
        migrations.AddField(
            model_name="booking",
            name="completion_date",
            field=models.DateTimeField(
                blank=True,
                help_text="When the rental was marked as completed.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="is_completed",
            field=models.BooleanField(
                default=False,
                help_text="Whether the rental is completed and tool returned.",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="comment",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="review",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="base.tool",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                default=5,
                help_text="Rating from 1 to 5 stars",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
