const tools= [
  {
    id: "tool01",
    name: "Tractor",
    category: "Heavy Machinery",
    description: "A large, powerful vehicle used for hauling farm equipment and various tasks like plowing and tilling.",
    dailyRentalPrice: 5000,
    availability: true,
    condition_rating: 4.5,
  },
  {
    id: "tool02",
    name: "Plow",
    category: "Tillage Implement",
    description: "An implement used to turn and loosen soil before sowing seeds or planting.",
    dailyRentalPrice: 800,
    availability: true,
    condition_rating: 4,
  },
  {
    id: "tool03",
    name: "Cultivator",
    category: "Tillage Implement",
    description: "Used to remove weeds and prepare the soil by breaking up the earth, allowing for better aeration.",
    dailyRentalPrice: 750,
    availability: false,
    condition_rating: 4.5,
  },
  {
    id: "tool04",
    name: "Combine Harvester",
    category: "Harvesting Machinery",
    description: "A machine that efficiently harvests crops by reaping, threshing, and winnowing in a single operation.",
    dailyRentalPrice: 10000,
    availability: true,
    condition_rating: 3.5,
  },
  {
    id: "tool05",
    name: "Sprayer Pump",
    image: "/images/Sprayer Pump.jpg",
    category: "Chemical Application",
    description: "Used to apply fertilizers, pesticides, and other chemicals to crops, available in various sizes.",
    dailyRentalPrice: 500,
    availability: true,
    condition_rating: 4.5,
  },
  {
    id: "tool06",
    name: "Rotary Tiller",
    category: "Tillage Implement",
    description: "A machine with rotating blades used for tilling and mixing soil to create a smooth seedbed.",
    dailyRentalPrice: 1200,
    availability: true,
    condition_rating: 5,
  },
  {
    id: "tool07",
    name: "Seed Drill",
    category: "Planting Equipment",
    description: "A specialized device for sowing seeds precisely into the soil at a controlled depth and rate.",
    dailyRentalPrice: 900,
    availability: false,
    condition_rating: 4.5,
  },
  {
    id: "tool08",
    name: "Harrow",
    category: "Tillage Implement",
    description: "Used after plowing to smooth out the soil surface and create a fine seedbed.",
    dailyRentalPrice: 650,
    availability: true,
    condition_rating: 3,
  },
  {
    id: "tool09",
    name: "Wheelbarrow",
    category: "Transport",
    description: "A hand-operated cart with one wheel for transporting heavy or bulky loads around the farm.",
    dailyRentalPrice: 100,
    availability: true,
    condition_rating: 2,
  },
  {
    id: "tool10",
    name: "Sickle",
    category: "Hand Tool",
    description: "A small hand tool with a curved blade and a handle, primarily used for harvesting grain.",
    dailyRentalPrice: 50,
    availability: true,
    condition_rating: 4,
  },
  {
    id: "tool11",
    name: "Shovel",
    category: "Hand Tool",
    description: "A multi-purpose tool for digging, lifting, and moving materials like soil, sand, and gravel.",
    dailyRentalPrice: 40,
    availability: true,
  },
  {
    id: "tool12",
    name: "Hand Fork",
    category: "Hand Tool",
    description: "Used for loosening soil around plants and mixing in manure or fertilizer.",
    dailyRentalPrice: 30,
    availability: true,
  },
  {
    id: "tool13",
    name: "Earth Auger",
    category: "Hand Tool",
    description: "A tool used for digging uniform holes in the ground for tasks like planting or installing fences.",
    dailyRentalPrice: 150,
    availability: true,
  },
  {
    id: "tool14",
    name: "Machete",
    category: "Hand Tool",
    description: "A versatile tool with a long, heavy blade used for clearing bushes, cutting branches, and harvesting crops.",
    dailyRentalPrice: 60,
    availability: true,
  },
  {
    id: "tool15",
    name: "Brush Cutter",
    category: "Heavy Machinery",
    description: "A machine used for clearing weeds, overgrown grass, and dense vegetation from a field.",
    dailyRentalPrice: 850,
    availability: false,
  },
]
export default tools;