export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_LIST_BOOKINGS_REQUEST = 'USER_LIST_BOOKINGS_REQUEST';
export const USER_LIST_BOOKINGS_SUCCESS = 'USER_LIST_BOOKINGS_SUCCESS';
export const USER_LIST_BOOKINGS_FAIL = 'USER_LIST_BOOKINGS_FAIL';

export const USER_LIST_TOOLS_REQUEST = 'USER_LIST_TOOLS_REQUEST';
export const USER_LIST_TOOLS_SUCCESS = 'USER_LIST_TOOLS_SUCCESS';
export const USER_LIST_TOOLS_FAIL = 'USER_LIST_TOOLS_FAIL';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_LIST_TOOL_BOOKINGS_REQUEST = 'USER_LIST_TOOL_BOOKINGS_REQUEST';
export const USER_LIST_TOOL_BOOKINGS_SUCCESS = 'USER_LIST_TOOL_BOOKINGS_SUCCESS';
export const USER_LIST_TOOL_BOOKINGS_FAIL = 'USER_LIST_TOOL_BOOKINGS_FAIL';